version: 2.0

jobs:
    build:
        branches:
            only:
                - source
        docker:
            - image: cibuilds/hugo:latest
        working_directory: ~/abeltshauser-lagersysteme.github.io
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "ab:bc:f1:a5:49:fc:9c:a7:54:66:8e:63:74:0c:a6:f4"
            - checkout
            - run:
                name: Get current site
                working_directory: ~/
                command: | 
                    git clone -b master git@github.com:abeltshauser-lagersysteme/abeltshauser-lagersysteme.github.io.git public
            - run:
                name: Generate site
                working_directory: ~/abeltshauser-lagersysteme.github.io
                command: HUGO_ENV=production hugo -d ~/public
            - run:
                name: Delete All SSH keys and Add the installed one
                command: ssh-add -D && ssh-add ~/.ssh/id_rsa_abbcf1a549fc9ca754668e63740ca6f4
            - deploy:
                name: Deploy to Github Pages & FTP
                working_directory: ~/public
                command: |
                    git config credential.helper 'cache --timeout=120'
                    git config user.email "k@b-coding.de"
                    git config user.name "Deployment Bot"
                    git add .
                    git commit --allow-empty -m "Trigger deployment"
                    git push -q git@github.com:abeltshauser-lagersysteme/abeltshauser-lagersysteme.github.io.git master

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: source
